dist: trusty
sudo: required
language: node_js

node_js:
  - "9"

install:
  - npm install -g truffle
  - npm install -g solhint

script:
  - npm install
  - truffle compile
  - solhint contracts/*.sol 
